今までの課題提出のリポジトリを統合し、第５回の課題提出
gitmrk2k6/raisetech pull request #1
Opened 2023-03-22 12:43 UTC by gitmrk2k6

## 今までの課題リポジトリを合体させました
- lecture05.mdで第５回の課題を提出します。よろしくお願いします。

2023-03-25 10:45 UTC, gitmrk2k6 commented on lecture05.md
lecture05.mdの構成図を訂正しました。確認をよろしくお願いします。

2023-03-26 03:14 UTC, MasatoshiMizumoto requested changes
1点ご対応お願いします！！

2023-03-26 03:14 UTC, MasatoshiMizumoto commented on lecture05.md
ALBについてですが、これはELB（Elastic Load Balancing）のアイコンですね！
これでもいいので、名前を合わせるか、ALBのアイコンにするかご対応ください！

2023-03-26 04:28 UTC, gitmrk2k6 commented
ELBと表記変更しました。

2023-03-26 09:24 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-03-27 13:19 UTC, merged